# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c89a0d0ee59686049c5a9b8a32e9ccb70b71f5ebceb4b65a8905d684fc0be6632de868d6cadeb4729a318f50b3c4612d6c76476b11b4dbb86adee4a5d37f0e4
  wot_api_app_id: 714da4639b2278de071bdd61850e3896

test:
  secret_key_base: 556c770076aee497161d0f244cd06d1de1f72cc63f3ff2fefa98995f061f87c1ac7080a01b81dea00939e11c50a00ea5f9c2436515a421570c44faf06337538e
  wot_api_app_id: 714da4639b2278de071bdd61850e3896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  wot_api_app_id: <%= ENV["WOT_API_APP_ID"] %>
